### ISSUE TITLE
Upgrade request to API 50

### ISSUE THREAD

**Issue by geza-mandli** [kgalant/PackageBuilder#18]
Dear @kgalant ,

This tool is extremely useful for me. Could I request you to upgrade the tool to API 50? There are new components / changes which are not included in api 48 and would be very useful if I could use your tool on the latest API. 👍 

Thanks for this great tool,
Géza

**Comment by kgalant** [comment]
Updated - even to API 51.... Please take it for a spin and let me know of any issues - did not have time to test extensively.
