### ISSUE TITLE
Feature Request - exclude metadata types

### ISSUE THREAD

**Issue by Vincent-Ip** [kgalant/PackageBuilder#7]
Hi there.  I really like this utility!  

I was wondering if there was a way to skip certain metadata types.  I see that the -mi option will allow you to specify what types you would like to see in the output, but I have a use case to pull down all meta data types with the exception of things like CustomObjectTranslation and Reports (CustomObjectTranslation is not needed as there are no meaningful translations created in the org and Reports as there are just too many).  I could list out all types in -mi, but it loses the dynamic discovery aspect that so nice about this tool.

I don't believe that the -sp parameter doesn't really work for this specific use case, but perhaps i'm wrong about that.

Thanks again for this really neat utility.

**Comment by kgalant** [comment]
-sp should work. The name pattern include runs against a string that looks
like this: <metadatatypeName>:<itemName>, so doing -sp Report:.* will skip
all reports.

Only other thing is that what's on the main branch right now has a bug when
you try to use multiple filters at the same time (-sp Report:.*,
CustomObjectTranslation:.*) so if you need that, go to the merge-git-commit
branch and take the JAR file from there, it's fixed there (we will likely
finalise the merge and get it into the master branch late this week or over
the weekend).

/Kim Galant

**Comment by Vincent-Ip** [comment]
awesome, it looks like it's working.

One note, in your sample configuration file in your documentation, you reference a "skipItems" as the configuration parameter for -sp.  That doesn't work.  I'm guessing it was the old name of the parameter.

Again, thanks for your help!
